/**
 * Auth API endpoints injected into the base RTK Query API.
 *
 * Endpoints:
 *   sendOtp       POST /auth/send-otp
 *   verifyOtp     POST /auth/verify-otp       (login existing user)
 *   register      POST /auth/register          (register + auto-login)
 *   adminLogin    POST /auth/admin/login
 *   refresh       POST /auth/refresh
 *   logout        POST /auth/logout
 *   getMe         GET  /auth/me
 */

import { baseApi } from "./baseApi";
import { setCredentials, clearCredentials } from "@/store/slices/authSlice";
import type {
  SendOtpInput,
  VerifyOtpInput,
  RegisterInput,
  AdminLoginInput,
  RefreshInput,
  AuthResponse,
  AuthTokens,
  AuthUser,
} from "@/lib/validators/auth.validators";

// ── Shared API response wrapper ────────────────────────────────────────────────
type ApiOk<T> = { ok: true; data: T };

export const authApi = baseApi.injectEndpoints({
  overrideExisting: false,
  endpoints: (build) => ({

    // ── Send OTP ───────────────────────────────────────────────────────────────
    sendOtp: build.mutation<
      ApiOk<{ message: string; otp?: string }>,
      SendOtpInput
    >({
      query: (body) => ({ url: "/auth/send-otp", method: "POST", body }),
    }),

    // ── Verify OTP (login) ─────────────────────────────────────────────────────
    verifyOtp: build.mutation<ApiOk<AuthResponse>, VerifyOtpInput>({
      query: (body) => ({ url: "/auth/verify-otp", method: "POST", body }),
      async onQueryStarted(_arg, { dispatch, queryFulfilled }) {
        try {
          const { data } = await queryFulfilled;
          dispatch(setCredentials(data.data));
          persistSession(data.data);
        } catch { /* handled by component */ }
      },
      invalidatesTags: ["Auth"],
    }),

    // ── Register ───────────────────────────────────────────────────────────────
    register: build.mutation<ApiOk<AuthResponse>, RegisterInput>({
      query: (body) => ({ url: "/auth/register", method: "POST", body }),
      async onQueryStarted(_arg, { dispatch, queryFulfilled }) {
        try {
          const { data } = await queryFulfilled;
          dispatch(setCredentials(data.data));
          persistSession(data.data);
        } catch { /* handled by component */ }
      },
      invalidatesTags: ["Auth"],
    }),

    // ── Admin Login ────────────────────────────────────────────────────────────
    adminLogin: build.mutation<ApiOk<AuthResponse>, AdminLoginInput>({
      query: (body) => ({ url: "/auth/admin/login", method: "POST", body }),
      async onQueryStarted(_arg, { dispatch, queryFulfilled }) {
        try {
          const { data } = await queryFulfilled;
          dispatch(setCredentials(data.data));
          persistSession(data.data);
        } catch { /* handled by component */ }
      },
      invalidatesTags: ["Auth"],
    }),

    // ── Silent Refresh ─────────────────────────────────────────────────────────
    refresh: build.mutation<ApiOk<{ tokens: AuthTokens }>, RefreshInput>({
      query: (body) => ({ url: "/auth/refresh", method: "POST", body }),
    }),

    // ── Logout ─────────────────────────────────────────────────────────────────
    logout: build.mutation<ApiOk<{ message: string }>, { refreshToken: string }>({
      query: (body) => ({ url: "/auth/logout", method: "POST", body }),
      async onQueryStarted(_arg, { dispatch, queryFulfilled }) {
        // Optimistically clear local state even if API call fails
        dispatch(clearCredentials());
        clearPersistedSession();
        try { await queryFulfilled; } catch { /* already cleared */ }
      },
      invalidatesTags: ["Auth", "User"],
    }),

    // ── Get Current User ───────────────────────────────────────────────────────
    getMe: build.query<ApiOk<{ user: AuthUser }>, void>({
      query: () => ({ url: "/auth/me", method: "GET" }),
      providesTags: ["User"],
    }),

  }),
});

// ── Persist tokens to localStorage + cookie (for middleware) ──────────────────
const SESSION_KEY = "motomart_session";

function persistSession({ user, tokens }: AuthResponse) {
  if (typeof window === "undefined") return;
  const payload = { user, accessToken: tokens.accessToken, refreshToken: tokens.refreshToken };
  localStorage.setItem(SESSION_KEY, JSON.stringify(payload));
  // Cookie carries the access token so Next.js middleware can verify it server-side
  document.cookie = `${SESSION_KEY}=${encodeURIComponent(tokens.accessToken)}; path=/; max-age=${tokens.expiresIn}; SameSite=Lax`;
}

function clearPersistedSession() {
  if (typeof window === "undefined") return;
  localStorage.removeItem(SESSION_KEY);
  document.cookie = `${SESSION_KEY}=; path=/; max-age=0`;
}

// ── Exported hooks (auto-generated by RTK Query) ───────────────────────────────
export const {
  useSendOtpMutation,
  useVerifyOtpMutation,
  useRegisterMutation,
  useAdminLoginMutation,
  useRefreshMutation,
  useLogoutMutation,
  useGetMeQuery,
} = authApi;
