import { Part, Order, Review } from "./types";

export const BIKE_BRANDS = [
  "Honda",
  "Hero",
  "Bajaj",
  "TVS",
  "Yamaha",
  "Suzuki",
  "Royal Enfield",
  "Universal",
] as const;

export const CATEGORIES = [
  "Brakes",
  "Engine Parts",
  "Electrical",
  "Filters",
  "Body Parts",
  "Tyres & Tubes",
  "Oils & Lubricants",
] as const;

export const BIKE_MODELS: Record<string, string[]> = {
  Honda: ["Honda Activa 6G", "Honda CB Shine", "Honda Dio", "Honda Unicorn", "Honda CB Hornet 160R"],
  Hero: ["Hero Splendor Plus", "Hero HF Deluxe", "Hero Passion Pro", "Hero Glamour", "Hero Xpulse 200"],
  Bajaj: ["Bajaj Pulsar 150", "Bajaj Pulsar NS200", "Bajaj CT100", "Bajaj Dominar 400", "Bajaj Avenger 220"],
  TVS: ["TVS Apache RTR 160", "TVS Apache RTR 200", "TVS Jupiter", "TVS XL100", "TVS Ntorq 125"],
  Yamaha: ["Yamaha FZ-S", "Yamaha R15", "Yamaha MT-15", "Yamaha Fascino 125", "Yamaha SZ-RR"],
  Suzuki: ["Suzuki Access 125", "Suzuki Gixxer", "Suzuki Intruder 150", "Suzuki Burgman Street"],
  "Royal Enfield": ["Royal Enfield Classic 350", "Royal Enfield Bullet 350", "Royal Enfield Meteor 350", "Royal Enfield Himalayan"],
};

export const parts: Part[] = [
  {
    id: "1",
    name: "Honda Activa 6G Brake Pad Set",
    sku: "BRK-HON-ACT6G-001",
    category: "Brakes",
    description:
      "High-performance ceramic brake pads designed specifically for Honda Activa 6G. Provides superior braking power, reduced noise, and longer life. OEM-quality fit with easy installation.",
    price: 450,
    mrp: 550,
    stock: 45,
    minStock: 10,
    images: [],
    compatibleBikes: ["Honda Activa 6G", "Honda Activa 5G", "Honda Dio"],
    brand: "Honda",
    rating: 4.5,
    reviewCount: 128,
    isFeatured: true,
    isSale: true,
  },
  {
    id: "2",
    name: "Hero Splendor Plus Engine Oil Filter",
    sku: "FLT-HER-SPL-001",
    category: "Filters",
    description:
      "Genuine quality engine oil filter for Hero Splendor Plus. Ensures clean oil circulation, protects engine components, and extends engine life. Compatible with most Hero 100cc bikes.",
    price: 120,
    mrp: 150,
    stock: 8,
    minStock: 15,
    images: [],
    compatibleBikes: ["Hero Splendor Plus", "Hero HF Deluxe", "Hero Passion Pro"],
    brand: "Hero",
    rating: 4.2,
    reviewCount: 89,
    isFeatured: true,
    isSale: false,
  },
  {
    id: "3",
    name: "Universal H4 Headlight Bulb 35W",
    sku: "ELC-UNV-H4-35W",
    category: "Electrical",
    description:
      "High-brightness H4 halogen headlight bulb 35/35W. White light output with improved visibility. Universal fit for most 2-wheelers. Long life up to 500 hours.",
    price: 85,
    mrp: 120,
    stock: 120,
    minStock: 20,
    images: [],
    compatibleBikes: ["Honda Activa 6G", "Hero Splendor Plus", "Bajaj Pulsar 150", "TVS Apache RTR 160"],
    brand: "Universal",
    rating: 4.0,
    reviewCount: 245,
    isFeatured: true,
    isSale: true,
  },
  {
    id: "4",
    name: "Bajaj Pulsar 150 Chain Sprocket Kit",
    sku: "ENG-BAJ-P150-CSK",
    category: "Engine Parts",
    description:
      "Complete chain and sprocket kit for Bajaj Pulsar 150. Includes front sprocket, rear sprocket, and heavy-duty drive chain. Heat-treated steel for maximum durability and performance.",
    price: 890,
    mrp: 1100,
    stock: 22,
    minStock: 5,
    images: [],
    compatibleBikes: ["Bajaj Pulsar 150", "Bajaj Pulsar 150 Twin Disc"],
    brand: "Bajaj",
    rating: 4.7,
    reviewCount: 67,
    isFeatured: true,
    isSale: true,
  },
  {
    id: "5",
    name: "TVS Apache RTR Clutch Plate Set",
    sku: "ENG-TVS-APR-CPS",
    category: "Engine Parts",
    description:
      "Premium friction clutch plate set for TVS Apache RTR series. Smooth engagement, reduced clutch judder, and consistent performance. High-temperature resistant material.",
    price: 680,
    mrp: 850,
    stock: 3,
    minStock: 8,
    images: [],
    compatibleBikes: ["TVS Apache RTR 160", "TVS Apache RTR 200", "TVS Apache RTR 160 4V"],
    brand: "TVS",
    rating: 4.3,
    reviewCount: 43,
    isFeatured: false,
    isSale: false,
  },
  {
    id: "6",
    name: "Honda CB Shine Air Filter",
    sku: "FLT-HON-CBS-AF",
    category: "Filters",
    description:
      "High-efficiency air filter for Honda CB Shine. Captures dust and particles up to 99.5% efficiency. Washable and reusable. Improves airflow and protects the engine from contaminants.",
    price: 220,
    mrp: 280,
    stock: 35,
    minStock: 10,
    images: [],
    compatibleBikes: ["Honda CB Shine", "Honda CB Shine SP", "Honda Livo"],
    brand: "Honda",
    rating: 4.4,
    reviewCount: 112,
    isFeatured: false,
    isSale: false,
  },
  {
    id: "7",
    name: "Yamaha FZ-S Front Disc Brake Rotor",
    sku: "BRK-YAM-FZS-DBR",
    category: "Brakes",
    description:
      "Precision-machined front disc brake rotor for Yamaha FZ-S. Wave-petal design for better heat dissipation and stopping power. Rust-resistant coating for long life.",
    price: 1250,
    mrp: 1500,
    stock: 15,
    minStock: 5,
    images: [],
    compatibleBikes: ["Yamaha FZ-S", "Yamaha FZ 25", "Yamaha MT-15"],
    brand: "Yamaha",
    rating: 4.6,
    reviewCount: 34,
    isFeatured: false,
    isSale: true,
  },
  {
    id: "8",
    name: "Royal Enfield Classic 350 Rear Tyre",
    sku: "TYR-RE-C350-R",
    category: "Tyres & Tubes",
    description:
      "100/90-18 tubeless tyre for Royal Enfield Classic 350. Deep tread pattern for superior grip on wet and dry roads. Long mileage compound.",
    price: 2800,
    mrp: 3200,
    stock: 10,
    minStock: 4,
    images: [],
    compatibleBikes: ["Royal Enfield Classic 350", "Royal Enfield Bullet 350"],
    brand: "Royal Enfield",
    rating: 4.5,
    reviewCount: 28,
    isFeatured: false,
    isSale: false,
  },
  {
    id: "9",
    name: "Suzuki Access 125 Speedometer Cable",
    sku: "ELC-SUZ-ACC-SC",
    category: "Electrical",
    description:
      "Durable speedometer cable for Suzuki Access 125. Smooth operation, kink-resistant steel braiding, and correct length for proper fitment.",
    price: 180,
    mrp: 220,
    stock: 0,
    minStock: 10,
    images: [],
    compatibleBikes: ["Suzuki Access 125", "Suzuki Burgman Street"],
    brand: "Suzuki",
    rating: 3.9,
    reviewCount: 19,
    isFeatured: false,
    isSale: false,
  },
  {
    id: "10",
    name: "Hero Glamour Silencer Assembly",
    sku: "BDY-HER-GLM-SIL",
    category: "Body Parts",
    description:
      "Complete exhaust silencer assembly for Hero Glamour 125. OEM-spec fitment, corrosion-resistant coating, and proper sound dampening for a stock exhaust note.",
    price: 1680,
    mrp: 2000,
    stock: 7,
    minStock: 3,
    images: [],
    compatibleBikes: ["Hero Glamour 125", "Hero Glamour FI"],
    brand: "Hero",
    rating: 4.1,
    reviewCount: 22,
    isFeatured: false,
    isSale: false,
  },
  {
    id: "11",
    name: "10W-30 Engine Oil 1L (Semi-Synthetic)",
    sku: "OIL-UNV-10W30-1L",
    category: "Oils & Lubricants",
    description:
      "Semi-synthetic 10W-30 engine oil for most 4-stroke 2-wheelers. JASO MA2 certified. Provides excellent wear protection, thermal stability, and clean engine performance.",
    price: 320,
    mrp: 380,
    stock: 80,
    minStock: 25,
    images: [],
    compatibleBikes: ["Honda Activa 6G", "Hero Splendor Plus", "Bajaj Pulsar 150", "TVS Apache RTR 160"],
    brand: "Universal",
    rating: 4.4,
    reviewCount: 310,
    isFeatured: false,
    isSale: false,
  },
  {
    id: "12",
    name: "Bajaj Pulsar NS200 Front Fork Assembly",
    sku: "BDY-BAJ-NS200-FFA",
    category: "Body Parts",
    description:
      "Complete front fork assembly for Bajaj Pulsar NS200. Includes both fork legs, springs, and seals. Restores original suspension geometry and ride quality.",
    price: 3500,
    mrp: 4200,
    stock: 5,
    minStock: 2,
    images: [],
    compatibleBikes: ["Bajaj Pulsar NS200", "Bajaj Pulsar AS200"],
    brand: "Bajaj",
    rating: 4.3,
    reviewCount: 15,
    isFeatured: false,
    isSale: true,
  },
];

export const orders: Order[] = [
  {
    id: "ORD-2024-001",
    customer: "Rajesh Kumar",
    phone: "9876543210",
    address: "45, Shivaji Nagar, Near Bus Stand",
    pincode: "411005",
    city: "Pune",
    items: [{ part: parts[0], quantity: 2 }, { part: parts[2], quantity: 1 }],
    total: 985,
    status: "delivered",
    createdAt: "2024-07-10",
  },
  {
    id: "ORD-2024-002",
    customer: "Priya Sharma",
    phone: "9823456789",
    address: "12, MG Road, 2nd Floor",
    pincode: "560001",
    city: "Bengaluru",
    items: [{ part: parts[3], quantity: 1 }],
    total: 890,
    status: "dispatched",
    createdAt: "2024-07-11",
  },
  {
    id: "ORD-2024-003",
    customer: "Amit Patel",
    phone: "9712345678",
    address: "78, Gandhi Road, Sector 12",
    pincode: "380015",
    city: "Ahmedabad",
    items: [{ part: parts[1], quantity: 3 }, { part: parts[5], quantity: 1 }],
    total: 580,
    status: "confirmed",
    createdAt: "2024-07-12",
  },
  {
    id: "ORD-2024-004",
    customer: "Sunita Rao",
    phone: "9543216789",
    address: "23, Anna Salai, Teynampet",
    pincode: "600018",
    city: "Chennai",
    items: [{ part: parts[4], quantity: 1 }],
    total: 680,
    status: "pending",
    createdAt: "2024-07-12",
  },
  {
    id: "ORD-2024-005",
    customer: "Vikram Singh",
    phone: "9988776655",
    address: "5, Connaught Place",
    pincode: "110001",
    city: "Delhi",
    items: [{ part: parts[6], quantity: 1 }, { part: parts[10], quantity: 2 }],
    total: 1890,
    status: "cancelled",
    createdAt: "2024-07-09",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    user: "Manish K.",
    rating: 5,
    comment: "Ekdum sahi part hai! Activa mein fit hua aur braking bahut achhi ho gayi. Fast delivery bhi mili.",
    date: "2024-07-08",
  },
  {
    id: "r2",
    user: "Deepak R.",
    rating: 4,
    comment: "Good quality brake pads. Genuine part, no noise. Would recommend to others.",
    date: "2024-07-05",
  },
  {
    id: "r3",
    user: "Sanjay M.",
    rating: 5,
    comment: "MotoMart ne bahut jaldi deliver kiya. Part original lagta hai. Kaafi satisfied hoon.",
    date: "2024-07-01",
  },
];

export const categoryIcons: Record<string, string> = {
  Brakes: "🛞",
  "Engine Parts": "⚙️",
  Electrical: "⚡",
  Filters: "🔧",
  "Body Parts": "🏍️",
  "Tyres & Tubes": "🔄",
  "Oils & Lubricants": "🛢️",
};

export const categoryPartCounts: Record<string, number> = {
  Brakes: 48,
  "Engine Parts": 124,
  Electrical: 89,
  Filters: 67,
  "Body Parts": 93,
  "Tyres & Tubes": 41,
  "Oils & Lubricants": 28,
};
